version: '3.7'

services:
  database:
    container_name: database
    restart: always
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin

    image: postgres:14.12-alpine3.19

    volumes:
      - ./database/data:/var/lib/postgresql/data