FROM python:latest

RUN mkdir -p /home/app
WORKDIR /home/app
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

EXPOSE 8000